name: ProdBuildDockerImageAndPublish

on:
 # push:
    #branches: [ main ]
 # pull_request:
   # branches: [ main ]
  schedule:
    - cron: '0 11 * * 2,4' # run at 2 AM UTC
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-container:
    runs-on: ubuntu-latest
    container: docker:latest
    steps:
    - uses: actions/checkout@v4     
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: richjjoh/hyde:latest
